### ISSUE TITLE
Crash in 'TestAccAWSCloudWatchEventPermission_Disappears' when running unit tests

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

```console
 make test
==> Checking that code complies with gofmt requirements...
go test ./... -timeout=30s -parallel=4
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
...
--- FAIL: TestAccAWSCloudWatchEventPermission_Disappears (0.00s)
panic: runtime error: slice bounds out of range [:64] with length 63 [recovered]
	panic: runtime error: slice bounds out of range [:64] with length 63

goroutine 938 [running]:
testing.tRunner.func1(0xc00116b900)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x64e3ba0, 0xc000109b40)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/terraform-providers/terraform-provider-aws/aws.TestAccAWSCloudWatchEventPermission_Disappears(0xc00116b900)
	/development/golang/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_cloudwatch_event_permission_test.go:254 +0x366
testing.tRunner(0xc00116b900, 0x6b730c0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	9.658s
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	(cached)
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	(cached)
FAIL
make: *** [test] Error 1
```

**Comment by ewbankkit** [comment]
This is the line of code: https://github.com/terraform-providers/terraform-provider-aws/blob/baa8f8c81aadcad7a3ad66552f1597e835ae548c/aws/resource_aws_cloudwatch_event_permission_test.go#L254

There's no guarantee that `acctest.RandomWithPrefix()` returns a string of any particular length.

I found one other dangerous looking call: https://github.com/terraform-providers/terraform-provider-aws/blob/baa8f8c81aadcad7a3ad66552f1597e835ae548c/aws/resource_aws_elasticsearch_domain_test.go#L92
