### ISSUE TITLE
crash *after* route53 creates an hosted zone

### ISSUE THREAD

**Issue by giulianozor** [terraform-providers/terraform-provider-aws#12361]
### Terraform Version
* Terraform v0.12.23
+ provider.aws v2.52.0

### Affected Resource(s)
* aws_route53_zone

### Terraform Configuration Files

Full repo at https://github.com/giulianozor/aws_route53_zone_crash

```
provider "aws" {
  access_key                  = "mock_access_key"
  region                      = "ap-northeast-1"
  s3_force_path_style         = true
  secret_key                  = "mock_secret_key"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ...
    route53        = "http://localhost:4580"
     ...
     }
}

terraform {
  backend "local" {
    path = "./terraform.tfstate"
  }
}

resource "aws_route53_zone" "zone" {
    name = "ciccio.com."
}
```

### Debug Output

```
aws_route53_zone.zone: Creating...
Error: rpc error: code = Canceled desc = context canceled
panic: runtime error: invalid memory address or nil pointer dereference
```

### Panic Output

Full crash.log in repo
Full pcap in repo too, just in case

### Expected Behavior

Just create the hosted zone and exit without errors.

### Actual Behavior

The zone is actually created in localstack, but the provider exits with status code 2

### Steps to Reproduce
0. start localstack with the provided docker-composer
```
(on mac you need to export TMPDIR to somwhere writable in your shared folders list like export TMPDIR=~/tmp)
docker-compose up
```
1. terraform init
2. terraform apply

### Important Factoids

OS is MacOs 10.15.3
Localstack is 
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack   latest              924c1deae9e4        6 hours ago         924MB
```
CLI works fine, no errors 
```
awslocal route53 create-hosted-zone --name ciccio --caller-reference 111

{
    "HostedZone": {
        "ResourceRecordSetCount": 0,
        "Config": {
            "PrivateZone": false
        },
        "Id": "/hostedzone/4HVL4WG3QNVF3IL",
        "Name": "ciccio."
    },
    "DelegationSet": {
        "NameServers": [
            "moto.test.com"
        ]
    }
}
```
I tried to create a vpc and that worked

**Comment by ewbankkit** [comment]
Relevant part of the crash log:

```
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 2020/03/12 16:24:31 [DEBUG] Creating Route53 hosted zone: {
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:   CallerReference: "terraform-20200312072431251700000001",
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:   HostedZoneConfig: {
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:     Comment: "Managed by Terraform"
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:   },
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:   Name: "ciccio.com."
2020-03-12T16:24:31.251+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: }
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 2020/03/12 16:24:31 [DEBUG] [aws-sdk-go] DEBUG: Request route53/CreateHostedZone Details:
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: POST /2013-04-01/hostedzone HTTP/1.1
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Host: localhost:4580
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: User-Agent: aws-sdk-go/1.29.18 (go1.13.7; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.23 (+https://www.terraform.io)
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Content-Length: 276
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Authorization: AWS4-HMAC-SHA256 Credential=mock_access_key/20200312/us-east-1/route53/aws4_request, SignedHeaders=content-length;host;x-amz-date, Signature=f5c2937f1d7fc7959c3b46ca5f596c57f7731fd20694911e4ddefd7e784a6779
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: X-Amz-Date: 20200312T072431Z
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Accept-Encoding: gzip
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: <CreateHostedZoneRequest xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><CallerReference>terraform-20200312072431251700000001</CallerReference><HostedZoneConfig><Comment>Managed by Terraform</Comment></HostedZoneConfig><Name>ciccio.com.</Name></CreateHostedZoneRequest>
2020-03-12T16:24:31.252+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: -----------------------------------------------------
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 2020/03/12 16:24:31 [DEBUG] [aws-sdk-go] DEBUG: Response route53/CreateHostedZone Details:
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: ---[ RESPONSE ]--------------------------------------
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: HTTP/1.0 201 CREATED
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Connection: close
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Content-Length: 542
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Access-Control-Allow-Origin: *
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Content-Type: text/html; charset=utf-8
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Date: Thu, 12 Mar 2020 07:24:31 GMT
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: Server: Werkzeug/1.0.0 Python/3.8.2
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: -----------------------------------------------------
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 2020/03/12 16:24:31 [DEBUG] [aws-sdk-go] <CreateHostedZoneResponse xmlns="https://route53.amazonaws.com/doc/2012-12-12/">
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:    <HostedZone>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       <Id>/hostedzone/NL4IZJ1ADS99MAH</Id>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       <Name>ciccio.com.</Name>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       <ResourceRecordSetCount>0</ResourceRecordSetCount>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       <Config>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:         
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:             <Comment>Managed by Terraform</Comment>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:         
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:         <PrivateZone>False</PrivateZone>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       </Config>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:    </HostedZone>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:    <DelegationSet>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       <NameServers>
2020-03-12T16:24:31.276+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:          <NameServer>moto.test.com</NameServer>
2020-03-12T16:24:31.277+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:       </NameServers>
2020-03-12T16:24:31.277+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4:    </DelegationSet>
2020-03-12T16:24:31.277+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: </CreateHostedZoneResponse>
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4bd32d2]
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: goroutine 73 [running]:
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRoute53ZoneCreate(0xc000165340, 0x51fa760, 0xc0002f9900, 0x2, 0xa26cd60)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_route53_zone.go:145 +0x4e2
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00069ec80, 0xc000155360, 0xc000c8fb40, 0x51fa760, 0xc0002f9900, 0xc000519d01, 0xc000b48870, 0xc000519df0)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0007cec00, 0xc000ce5918, 0xc000155360, 0xc000c8fb40, 0xc0000d8e08, 0xc00013a148, 0x57f8860)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00056ea28, 0x6e58080, 0xc000a49890, 0xc000b40300, 0xc00056ea28, 0xc000a49890, 0xc0009b5a80)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x635f2e0, 0xc00056ea28, 0x6e58080, 0xc000a49890, 0xc000b402a0, 0x0, 0x6e58080, 0xc000a49890, 0xc0004b0160, 0x145)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003de000, 0x6e78cc0, 0xc0001ef980, 0xc000ae1500, 0xc0005124b0, 0xa240100, 0x0, 0x0, 0x0)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0003de000, 0x6e78cc0, 0xc0001ef980, 0xc000ae1500, 0x0)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1275 +0xd97
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001405c0, 0xc0003de000, 0x6e78cc0, 0xc0001ef980, 0xc000ae1500)
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:710 +0xbb
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-03-12T16:24:31.279+0900 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020/03/12 16:24:31 [DEBUG] aws_route53_zone.zone: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
```

Relevant code:

https://github.com/terraform-providers/terraform-provider-aws/blob/654cc23a38444d4836155d6a2243e3976b5f3992/aws/resource_aws_route53_zone.go#L136-L147

**Comment by loivis** [comment]
From the SDK, `ChangeInfo` should always be there as required field.

```
type CreateHostedZoneOutput struct {
    // ChangeInfo is a required field
    ChangeInfo *ChangeInfo `type:"structure" required:"true"`
}
```

It's no big issue to fix, but sounds more like an upstream issue that localstack doesn't 100% mimic original behaviour?

**Comment by giulianozor** [comment]
> From the SDK, `ChangeInfo` should always be there as required field. But it was not seen in the response.
> 
> ```
> type CreateHostedZoneOutput struct {
>     // ChangeInfo is a required field
>     ChangeInfo *ChangeInfo `type:"structure" required:"true"`
> }
> ```
> 
> It's no big issue to fix, but sounds more like an upstream issue that localstack doesn't 100% mimic original behaviour?

I think this is shoyld be fixed at the localstack level. There is no good reason to deviate from the real aws to accomodate things for localstack

**Comment by bflad** [comment]
Please note that while we try not to introduce very special logic for supporting APIs like LocalStack, code safety is also important, and I have submitted https://github.com/terraform-providers/terraform-provider-aws/pull/12634 to fix this in the resource.
