### ISSUE TITLE
Glue: Can't create new table, err: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by Mikita-Kharitonau** [terraform-providers/terraform-provider-aws#12607]
### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.55.0
```

### Affected Resource(s)

* aws_glue_catalog_table

#### terraform.tf
```hcl
terraform {
  required_version = "~> 0.12.0"
}

provider "aws" {
  region                  = "us-east-1"
  version                 = "~> 2.0"
}

resource "aws_glue_catalog_table" "issue_table" {
  database_name = "issue_db"
  name          = "issue_table"
  owner         = "hadoop"
  parameters    = {
    "EXTERNAL"                             = "TRUE"
  }
  retention     = 0
  table_type    = "EXTERNAL_TABLE"

  partition_keys {
    name = "dt"
    type = "string"
  }

  storage_descriptor {
    bucket_columns            = []
    compressed                = false
    input_format              = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    location                  = "s3://issue_bucket/issue_table"
    number_of_buckets         = -1
    output_format             = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
    parameters                = {}
    stored_as_sub_directories = false

    columns {
      name = "issue_column"
      type = "string"
    }

    ser_de_info {
      name = "SerDe"
      parameters            = {
        "serialization.format" = "1"
      }
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
    }

    skewed_info {
      skewed_column_names               = []
      skewed_column_value_location_maps = {}
      skewed_column_values              = []
    }
  }
}
```

### Debug Output
https://gist.github.com/Mikita-Kharitonau/5639ff364dcd8e5463a4c12aae0bbe49

### Panic Output
https://gist.github.com/Mikita-Kharitonau/d9bd5f90ce53713f15f9ed7af988898c

### Expected Behavior

Glue table should be created

### Actual Behavior

Terraform crash with
`err: rpc error: code = Unavailable desc = transport is closing`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -target aws_glue_catalog_table.issue_table`

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/11784

**Comment by Mikita-Kharitonau** [comment]
Seems like this is related to https://github.com/terraform-providers/terraform-provider-aws/issues/11784. But we can update existing tables, while can't create a new one.

**Comment by bflad** [comment]
Hi @Mikita-Kharitonau 👋 Thank you for reporting this and sorry you ran into trouble here. The stack trace does look the same as #11784, so to consolidate efforts and discussions, going to consolidate this with the previous issue.

To apply an immediate fix in your configuration, you should be able to completely remove the `skewed_info` configuration block that contains all "empty" arguments, e.g.

```hcl
resource "aws_glue_catalog_table" "issue_table" {
  # ... other configuration ...

  storage_descriptor {
    # ... remove below ...
    skewed_info {
      skewed_column_names               = []
      skewed_column_value_location_maps = {}
      skewed_column_values              = []
    }
  }
}
```

Stacktrace:

```
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: panic: interface conversion: interface {} is nil, not map[string]interface {}
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: 
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: goroutine 105 [running]:
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.expandGlueSkewedInfo(0xc000d39b70, 0x1, 0x1, 0xb)
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_catalog_table.go:533 +0x6dc
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.expandGlueStorageDescriptor(0xc000d399f0, 0x1, 0x1, 0x469bf60)
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_catalog_table.go:440 +0x5ee
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.expandGlueTableInput(0xc0000d3f10, 0xc000d39900)
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_catalog_table.go:359 +0x1f5
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsGlueCatalogTableCreate(0xc0000d3f10, 0x4e24fc0, 0xc0002fc500, 0x2, 0x96ee420)
2020-04-01T12:56:40.092+0300 [DEBUG] plugin.terraform-provider-aws_v2.55.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_catalog_table.go:235 +0x1ae
```
