### ISSUE TITLE
Terraform crashing when creating bucket in MinIO

### ISSUE THREAD

**Issue by aboutte** [terraform-providers/terraform-provider-aws#12701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Terraform Configuration Files

```hcl
provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  s3_force_path_style         = true

  endpoints {
    s3 = "https://minio.example.com"
  }
}

resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
}

```

### Panic Output

https://gist.github.com/aboutte/0532c669df1d66c411f35eb9eadc33fa

### Expected Behavior

- terraform creates the bucket
- bucket gets stored in state

### Actual Behavior

- terraform creates the bucket
- terraform crashes when receiving response from Minio

### Steps to Reproduce

- deploy minio
- review the steps and terraform provided in the gist above

**Comment by bflad** [comment]
This appears to relate to key-only tags and should be addressed by https://github.com/terraform-providers/terraform-provider-aws/pull/13868.

Relevant portion of crash log:

```
panic: runtime error: invalid memory address or nil pointer dereference
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x44620da]
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4:
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4: goroutine 101 [running]:
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4: github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags.KeyValueTags.Map(0xc000d33680, 0xc000d33680)
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags/key_value_tags.go:138 +0xda
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsS3BucketRead(0xc00044e380, 0x5a20720, 0xc000491900, 0x203000, 0x203000)
2020-04-06T20:24:52.915-0500 [DEBUG] plugin.terraform-provider-aws_v2.56.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_s3_bucket.go:1343 +0x3f63
```

**Comment by bflad** [comment]
The fix for this has been merged and will release later this week with version 3.5.0 of the Terraform AWS Provider.
