### ISSUE TITLE
aws_kinesis_firehose_delivery_stream: Crash

### ISSUE THREAD

**Issue by binarydud** [terraform-providers/terraform-provider-aws#3071]
### Terraform Version
1.7.1

### Affected Resource(s)
aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files
```hcl
resource "aws_kinesis_firehose_delivery_stream" "firehose_delivery_stream" {
  name = "firehose-delivery-stream"
  destination = "s3"
  s3_configuration {
    role_arn = "${aws_iam_role.firehose_role.arn}"
    bucket_arn = "${aws_s3_bucket.firehose_delivery_bucket.arn}"
    buffer_size = 5
    buffer_interval = 300
    compression_format = "GZIP"
  }
}
```

### Panic Output
```
panic: runtime error: invalid memory address or nil pointer dereference
2018-01-19T11:04:27.699-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27c986f]
2018-01-19T11:04:27.699-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4:
2018-01-19T11:04:27.699-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: goroutine 7792 [running]:
2018-01-19T11:04:27.699-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenFirehoseS3Configuration(0xc42388c250, 0xc42388c260, 0x0, 0xc42388c270, 0xc42388c280, 0x0, 0xc42388c2a0, 0x151927d, 0x3, 0x348f99b)
2018-01-19T11:04:27.699-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:193 +0x16f
2018-01-19T11:04:27.699-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenKinesisFirehoseDeliveryStream(0xc4218f6f50, 0xc420a872c0, 0xc420e04158, 0x0)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:304 +0x151c
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsKinesisFirehoseDeliveryStreamRead(0xc4218f6f50, 0x3082ca0, 0xc4249c0a00, 0xc4218f6f50, 0x0)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:1297 +0x323
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc424b70460, 0xc421d925a0, 0x3082ca0, 0xc4249c0a00, 0xc4217bc088, 0xc42557ea01, 0x80001082152)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x17e
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4226d8310, 0xc421d92550, 0xc421d925a0, 0x5d4a8b0, 0x0, 0x2a5)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42057ef20, 0xc425ae1870, 0xc425ae1960, 0x0, 0x0)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: reflect.Value.call(0xc42031ac60, 0xc4215a0998, 0x13, 0x3469695, 0x4, 0xc42557ef20, 0x3, 0x3, 0x0, 0x0, ...)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: reflect.Value.Call(0xc42031ac60, 0xc4215a0998, 0x13, 0xc4214cf720, 0x3, 0x3, 0xc421ba5f80, 0x33a6b80, 0xc4214cf750)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: net/rpc.(*service).call(0xc420f5d440, 0xc42364b770, 0xc42017ea08, 0xc420633c00, 0xc423fb7ba0, 0x2c0dc40, 0xc425ae1870, 0x16, 0x2c0dc80, 0xc425ae1960, ...)
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: created by net/rpc.(*Server).ServeCodec
2018-01-19T11:04:27.700-0700 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

### Expected Behavior
plan file output

### Actual Behavior
Panic Crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. upgrade provider to 1.7.1
1. `terraform plan`

### References
- GH-3005

**Comment by bflad** [comment]
This root cause here is that we are trying to deference an optional attribute (`Prefix`) from the Firehose API: https://docs.aws.amazon.com/firehose/latest/APIReference/API_S3DestinationDescription.html

I will submit a PR to fix this immediately. /cc @radeksimko

**Comment by bflad** [comment]
The has been merged into master and will be released with v1.8.0 of the provider (current ETA is end of this week).

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by favoretti** [comment]
Still doesn't work it seems...

```
terraform plan -target module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.global-infra: Refreshing state...
aws_s3_bucket.logbucket: Refreshing state... (ID: tntdigital-tools-platform-logs)
data.aws_iam_policy_document.firehose-trust-policy-doc: Refreshing state...
aws_iam_role.firehose-role: Refreshing state... (ID: tools-firehose-platform-logs)
data.aws_iam_policy_document.read_from_es: Refreshing state...
aws_elasticsearch_domain.es: Refreshing state... (ID: arn:aws:es:eu-west-1:156776894708:domain/tools-platform-logs)
aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: Refreshing state... (ID: arn:aws:firehose:eu-west-1:156776894708...ream/tools-platform-logs-public-access)

Error: Error refreshing state: 1 error(s) occurred:

* module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: 1 error(s) occurred:

* module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: unexpected EOF


panic: runtime error: invalid memory address or nil pointer dereference
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27caae3]
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4:
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: goroutine 173 [running]:
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenKinesisFirehoseDeliveryStream(0xc42014f6c0, 0xc4209c7200, 0xc4203c4a00, 0x0)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:296 +0x1a3
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsKinesisFirehoseDeliveryStreamRead(0xc42014f6c0, 0x3082ca0, 0xc42021c780, 0xc42014f6c0, 0x0)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:1297 +0x323
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420779ce0, 0xc420867360, 0x3082ca0, 0xc42021c780, 0xc42027b360, 0x1032101, 0x800204c9c80)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x17e
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420439b90, 0xc420867310, 0xc420867360, 0x5d48d90, 0x0, 0x756ea19ea3e6ea)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420174ca0, 0xc4208c3e30, 0xc4208c3f80, 0x0, 0x0)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: reflect.Value.call(0xc420376840, 0xc4201909c0, 0x13, 0x3469695, 0x4, 0xc42039af20, 0x3, 0x3, 0x0, 0x0, ...)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: reflect.Value.Call(0xc420376840, 0xc4201909c0, 0x13, 0xc42002e720, 0x3, 0x3, 0xc42005bc20, 0xc42005bce0, 0xc4203df5e0)
2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-02-01T16:03:57.889+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: net/rpc.(*service).call(0xc4207fe1c0, 0xc4207d65a0, 0xc4203a2d28, 0xc4203d8800, 0xc420175380, 0x2c0dc40, 0xc4208c3e30, 0x16, 0x2c0dc80, 0xc4208c3f80, ...)
2018-02-01T16:03:57.889+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-02-01T16:03:57.889+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: created by net/rpc.(*Server).ServeCodec
2018-02-01T16:03:57.889+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2018/02/01 16:03:57 [ERROR] root.firehose-logging: eval: *terraform.EvalRefresh, err: aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: unexpected EOF
2018/02/01 16:03:57 [ERROR] root.firehose-logging: eval: *terraform.EvalSequence, err: aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: unexpected EOF
2018/02/01 16:03:57 [TRACE] [walkRefresh] Exiting eval tree: module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs
2018/02/01 16:03:57 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/02/01 16:03:57 [TRACE] dag/walk: upstream errored, not walking "module.firehose-logging.output.firehose_stream_public_access_logs"
2018/02/01 16:03:57 [TRACE] dag/walk: upstream errored, not walking "root"
2018/02/01 16:03:57 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-02-01T16:03:57.892+0100 [DEBUG] plugin: plugin process exited: path=/Users/vlazarenko/work/TNT/terraform/terraform_plans/platform/tools-data/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.7.1_x4
2018-02-01T16:03:57.892+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

relevant code:

```resource "aws_kinesis_firehose_delivery_stream" "firehose-stream-public-access-logs" {
  name        = "${var.stage}-${var.service_name}-public-access"
  destination = "elasticsearch"

  elasticsearch_configuration {
    domain_arn = "${aws_elasticsearch_domain.es.arn}"
    role_arn   = "${aws_iam_role.firehose-role.arn}"
    index_name = "public-access-logs"
    type_name  = "log-entry"

    index_rotation_period = "OneDay"
    s3_backup_mode        = "AllDocuments"
  }

  s3_configuration {
    role_arn           = "${aws_iam_role.firehose-role.arn}"
    bucket_arn         = "${aws_s3_bucket.logbucket.arn}"
    prefix             = "public-access-logs/"
    buffer_size        = 5
    buffer_interval    = 400
    compression_format = "GZIP"
  }
}```

**Comment by favoretti** [comment]
Anything over 1.6.0 breaks, 1.6.0 works.

**Comment by bflad** [comment]
@favoretti the debug output you note above has `2018-02-01T16:03:57.888+0100 [DEBUG] plugin.terraform-provider-aws_v1.7.1_x4`, which is not the latest version of the provider. Can you double check on v1.8.0 please?

**Comment by favoretti** [comment]
@bflad Oh damn, sorry. Moment, 1.8.0 shows the same behavior. I'll give you the output in a bit.

**Comment by favoretti** [comment]
```
terraform plan -target module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.global-infra: Refreshing state...
aws_s3_bucket.logbucket: Refreshing state... (ID: tntdigital-tools-platform-logs)
data.aws_iam_policy_document.firehose-trust-policy-doc: Refreshing state...
aws_iam_role.firehose-role: Refreshing state... (ID: tools-firehose-platform-logs)
data.aws_iam_policy_document.read_from_es: Refreshing state...
aws_elasticsearch_domain.es: Refreshing state... (ID: arn:aws:es:eu-west-1:156776894708:domain/tools-platform-logs)
aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: Refreshing state... (ID: arn:aws:firehose:eu-west-1:156776894708...ream/tools-platform-logs-public-access)

Error: Error refreshing state: 1 error(s) occurred:

* module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: 1 error(s) occurred:

* module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: unexpected EOF


panic: runtime error: invalid memory address or nil pointer dereference
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x281c493]
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: goroutine 220 [running]:
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenKinesisFirehoseDeliveryStream(0xc420235110, 0xc4203f7c20, 0xc42051a260, 0x0)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:298 +0x1a3
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsKinesisFirehoseDeliveryStreamRead(0xc420235110, 0x30fe7e0, 0xc420011900, 0xc420235110, 0x0)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream.go:1299 +0x323
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4202e23f0, 0xc4203b0820, 0x30fe7e0, 0xc420011900, 0xc42043d488, 0xe64fe7367e5da201, 0x800992532b3)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x17e
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4201b90a0, 0xc4203b07d0, 0xc4203b0820, 0x5e9d000, 0x0, 0x0)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420724300, 0xc420659100, 0xc420659290, 0x0, 0x0)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: reflect.Value.call(0xc420334c60, 0xc42051a048, 0x13, 0x34f7a78, 0x4, 0xc420331f20, 0x3, 0x3, 0x0, 0x0, ...)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: reflect.Value.Call(0xc420334c60, 0xc42051a048, 0x13, 0xc420373f20, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: net/rpc.(*service).call(0xc420186040, 0xc42069c000, 0xc4201720a0, 0xc420162600, 0xc4206ef660, 0x2c733e0, 0xc420659100, 0x16, 0x2c73420, 0xc420659290, ...)
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: created by net/rpc.(*Server).ServeCodec
2018-02-01T16:55:55.237+0100 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2018/02/01 16:55:55 [ERROR] root.firehose-logging: eval: *terraform.EvalRefresh, err: aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: unexpected EOF
2018/02/01 16:55:55 [ERROR] root.firehose-logging: eval: *terraform.EvalSequence, err: aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs: unexpected EOF
2018/02/01 16:55:55 [TRACE] [walkRefresh] Exiting eval tree: module.firehose-logging.aws_kinesis_firehose_delivery_stream.firehose-stream-public-access-logs
2018/02/01 16:55:55 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/02/01 16:55:55 [TRACE] dag/walk: upstream errored, not walking "module.firehose-logging.output.firehose_stream_public_access_logs"
2018/02/01 16:55:55 [TRACE] dag/walk: upstream errored, not walking "root"
2018/02/01 16:55:55 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-02-01T16:55:55.241+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-02-01T16:55:55.241+0100 [DEBUG] plugin: plugin process exited: path=/Users/vlazarenko/work/TNT/terraform/terraform_plans/platform/tools-data/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.8.0_x4



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
@bflad  There you go

**Comment by radeksimko** [comment]
@favoretti Thanks for the report.

We generally prefer new issues to be opened for new crashes after upgrading. Even when it appears it's the same bug with the same root cause more often it's not. The only thing there's in common is that it's crash and it's caused by the same resource.

This is why I created #3226 -  can you jump in that thread and reply to my question there, please?
