### ISSUE TITLE
Crash when querying two separate environements

### ISSUE THREAD

**Issue by sysadmin1139** [terraform-providers/terraform-provider-aws#3966]
This afternoon we found a multiple environment Terraform crash. It doesn't seem to be consistent with where it bombs, or which specific resources trigger it. However, it does happen every time, and does it in two separate projects, with two separate terraform-provider-aws versions (1.12 and 1.7.1). All is with terraform 11.2

[GPGed crash-dumps](https://gist.github.com/sysadmin1139/43e89cce1ae530da2280c070c8df0679)

All it takes is a plan, because the crash happens during the check versus the statefiles. This feels like a change on the Amazon side, since this suddenly started happening today, and neither environment has seen significant changes other than strings to datafiles. No resource-definition changes.

```
panic: runtime error: invalid memory address or nil pointer dereference
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d4e5da]
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: goroutine 1209 [running]:
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenAwsLbTargetGroupResource(0xc4206f0150, 0x264d900, 0xc4201b6500, 0xc421186480, 0x0, 0x0)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:468 +0x5fa
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc4206f0150, 0x264d900, 0xc4201b6500, 0xc4206f0150, 0x0)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:276 +0x28b
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4208fd3b0, 0xc4211401e0, 0x264d900, 0xc4201b6500, 0xc420286f00, 0xc4202fe001, 0x80000000018)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x17e
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4208fd500, 0xc421140190, 0xc4211401e0, 0x7f2717763000, 0x0, 0x0)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420823440, 0xc42052c940, 0xc42052caf0, 0x0, 0x0)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: reflect.Value.call(0xc4201cc780, 0xc42000c5b8, 0x13, 0x2a69310, 0x4, 0xc420be2f20, 0x3, 0x3, 0x403a23, 0xc4204c0000, ...)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: reflect.Value.Call(0xc4201cc780, 0xc42000c5b8, 0x13, 0xc42072f720, 0x3, 0x3, 0xc42072f720, 0xc42072f728, 0xc4209a9b00)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: net/rpc.(*service).call(0xc420391ec0, 0xc4208048c0, 0xc420530970, 0xc420548480, 0xc4202d8780, 0x2198ce0, 0xc42052c940, 0x16, 0x2198d20, 0xc42052caf0, ...)
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: created by net/rpc.(*Server).ServeCodec
2018-03-28T17:48:33.304-0500 [DEBUG] plugin.terraform-provider-aws_v1.12.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by sysadmin1139** [comment]
Looks like this is a duplicate of #3954
