### ISSUE TITLE
Terraform Crashs with terraform.EvalSequence, err: unexpected EOF

### ISSUE THREAD

**Issue by wonderphil** [terraform-providers/terraform-provider-aws#4142]
### Terraform Version
Terraform v0.11.6

### Affected Resource(s)
* data.aws_db_snapshot.latest_bbstage_snapshot: 1 error(s) occurred:
* data.aws_db_snapshot.latest_bbstage_snapshot: unexpected EOF

### Debug Output
2018/04/10 15:33:09 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2018/04/10 15:33:09 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/04/10 15:33:09 [TRACE] [walkRefresh] Exiting eval tree: data.aws_db_snapshot.latest_bbstage_snapshot
2018/04/10 15:33:09 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/04/10 15:33:09 [TRACE] dag/walk: upstream errored, not walking "root"
2018-04-10T15:33:09.846+0100 [DEBUG] plugin: plugin process exited: path=/Users/pdavies/repos/infra_code/services/apli2_rw/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.14.0_x4
2018/04/10 15:33:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-04-10T15:33:10.021+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

See attached for more details

### Panic Output
[crash.log](https://github.com/terraform-providers/terraform-provider-aws/files/1895062/crash.log)

### Expected Behavior
Run apply and apply

### Actual Behavior
run apply and terraform crashs

### Steps to Reproduce
1. `terraform apply`

**Comment by bflad** [comment]
Relevant portion panic log:
```
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: goroutine 102 [running]:
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc420749260, 0xc4207228c0, 0x1, 0x1, 0xc420722812, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:502 +0x4ac
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc420749260, 0x37783d6, 0x16, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:473 +0x135
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc420749260, 0x37783d6, 0x16, 0x3673aa0, 0xc420526be8, 0x80000000000, 0x30, 0x30)
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:450 +0xa5
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc4207d67e0, 0x37783d6, 0x16, 0xc420735680, 0xc420a71618, 0x5412280, 0xc420749260, 0x1051e00, 0x0, 0x0)
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1158 +0xa0
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc4207d67e0, 0x37783d6, 0x16, 0xc420735680, 0xc4207a80c0, 0x5412280, 0xc420749260, 0xc400000000, 0x0, 0x0)
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:774 +0x49f
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4207d67e0, 0x0, 0xc420604000, 0x0, 0x33141a0, 0xc4201caa00, 0xc4204d0000, 0x63b88b0, 0x0)
2018-04-10T15:33:09.842+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x24a
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc4207168c0, 0x0, 0xc420604000, 0x33141a0, 0xc4201caa00, 0xc42080ef01, 0x3383340, 0x80000000010)
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0x187
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataDiff(0xc4202ed500, 0xc420086050, 0xc420604000, 0x63b6d90, 0x0, 0x0)
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:413 +0xa3
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataDiff(0xc420740480, 0xc420722010, 0xc4207220f0, 0x0, 0x0)
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:593 +0x4e
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: reflect.Value.call(0xc4203b0f60, 0xc42017a080, 0x13, 0x374cde0, 0x4, 0xc4203a9f20, 0x3, 0x3, 0x0, 0x0, ...)
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: reflect.Value.Call(0xc4203b0f60, 0xc42017a080, 0x13, 0xc420a40f20, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: net/rpc.(*service).call(0xc42018c600, 0xc4201741e0, 0xc42018e1e0, 0xc420182500, 0xc4207386a0, 0x2e3c860, 0xc420722010, 0x16, 0x2e3c8a0, 0xc4207220f0, ...)
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: created by net/rpc.(*Server).ServeCodec
2018-04-10T15:33:09.843+0100 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by bflad** [comment]
Hi @wonderphil 👋  Sorry you're running into trouble here. 

Can you confirm the relationship between these two (e.g. the `aws_db_snapshot` data source using some value from a `terraform_remote_state` data source)?

```
2018/04/10 15:33:07 [DEBUG] ReferenceTransformer: "data.aws_db_snapshot.latest_bbstage_snapshot" references: [data.terraform_remote_state.apli2db]
```

If so, can you please provide sanitized information for the following?
* `data.aws_db_snapshot.latest_bbstage_snapshot` configuration
* The Terraform state of the resource/output for the reference its pulling from `data.terraform_remote_state.apli2db`

This will help us track down this issue to fix it (although it'll likely be in Terraform core, not in the AWS provider). Thanks!

**Comment by wonderphil** [comment]
So i have the following to get the latest snapshot of another db but in the other state file
```
data "aws_db_snapshot" "latest_bbstage_snapshot" {

  db_instance_identifier = "${data.terraform_remote_state.apli2db.apli2_id}"

  most_recent            = true

}
```

Then the output from `data.terraform_remote_state.apli2db` looks like:
```
Outputs:

apli2_id = [
    bbstage-aws-apli2db-mysql-rds
]
```

Actual State:
```
....
"aws_db_instance.mysql_instance_db": {
                    "type": "aws_db_instance",
                    "depends_on": [
                        "aws_db_parameter_group.apli2_parameters",
                        "aws_security_group.mysql_vpc_sg",
                        "data.terraform_remote_state.aws_accounts",
                        "data.terraform_remote_state.shared_infra"
                    ],
                    "primary": {
                        "id": "bbstage-aws-apli2db-mysql-rds",
                        "attributes": {
                            "address": "db-mysql-rds.cnzfdajdstiu.eu-west-1.rds.amazonaws.com",
                            "allocated_storage": "1250",
                            "arn": "arn:aws:rds:eu-west-1:**********:db:bbstage-aws-apli2db-mysql-rds",
                            "auto_minor_version_upgrade": "true",
                            "availability_zone": "eu-west-1b",
                            "backup_retention_period": "2",
                            "backup_window": "03:27-03:57",
                            "ca_cert_identifier": "rds-ca-2015",
                            "copy_tags_to_snapshot": "true",
                            "db_subnet_group_name": "bbstage-shared-infra-rds-subnet-group",
                            "endpoint": "db-mysql-rds.cnzfdajdstiu.eu-west-1.rds.amazonaws.com:3306",
                            "engine": "mysql",
                            "engine_version": "5.6.35",
                            "final_snapshot_identifier": "bbstage-aws-apli2db-rds-final",
                            "hosted_zone_id": "Z29XKXDKYMONMX",
                            "iam_database_authentication_enabled": "false",
                            "id": "bbstage-aws-apli2db-mysql-rds",
                            "identifier": "bbstage-aws-apli2db-mysql-rds",
                            "instance_class": "db.m4.large",
                            "iops": "0",
                            "kms_key_id": "arn:aws:kms:eu-west-1:********:key/ef294786-b2e7-4a54-8326-6beac7ec3070",
                            "license_model": "general-public-license",
                            "maintenance_window": "sun:06:00-sun:06:30",
                            "monitoring_interval": "0",
                            "monitoring_role_arn": "arn:aws:iam::**********:role/bbstage-aws-rdsmonitoring-role",
                            "multi_az": "true",
                            "name": "prod_aws_apli2db_mysql_rds",
                            "option_group_name": "default:mysql-5-6",
                            "parameter_group_name": "db-param-group",
                            "password": "*************************",
                            "port": "3306",
                            "publicly_accessible": "false",
                            "replicas.#": "0",
                            "replicate_source_db": "",
                            "resource_id": "db-********",
                            "security_group_names.#": "0",
                            "skip_final_snapshot": "true",
                            "status": "available",
                            "storage_encrypted": "true",
                            "storage_type": "gp2",
                            "tags.%": "7",
                            "tags.Name": "db_rds",
                            "tags.bbenvironment": "bbstage",
                            "tags.bblocation": "aws",
                            "tags.bbowner": "com",
                            "tags.bbrole": "db",
                            "tags.bbservice": "ap",
                            "tags.terraform": "true",
                            "timezone": "",
                            "username": "username",
                            "vpc_security_group_ids.#": "1",
                            "vpc_security_group_ids.844457837": "sg-495d4e33"
                        },
                        "meta": {
                            "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                                "create": 2400000000000,
                                "delete": 2400000000000,
                                "update": 4800000000000
                            }
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.aws"
                }
....
```

**Comment by bflad** [comment]
Is this actually a list output?

```
apli2_id = [
    bbstage-aws-apli2db-mysql-rds
]
```

The resource is expecting a string input and potentially not properly handling the invalid type conversion with a normal error. Can you try:

```hcl
db_instance_identifier = "${data.terraform_remote_state.apli2db.apli2_id[0]}"
```

I believe this might be related to https://github.com/hashicorp/terraform/issues/17546

**Comment by wonderphil** [comment]
Yeah that got it working, Sorry should of seen that my-self.

**Comment by bflad** [comment]
Okay great. I'm going to close this issue in preference of the upstream issue. 👍
