### ISSUE TITLE
aws_emr_cluster Panic with Missing StateChangeReason Code/Message

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#4164]
This is not consistently occurring (since it depends on a failing configuration), but we can easily prevent it.

### Terraform Version

```
Terraform v0.11.3
+ provider.aws v1.13.0
```

### Affected Resource(s)

- aws_emr_cluster

### Terraform Configuration Files

```hcl
# Omitted
```

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fcb0c4]
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: goroutine 152 [running]:
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEMRClusterStateRefreshFunc.func1(0xc420041f20, 0x1, 0x0, 0x0, 0x10, 0xc4202d6ee0)
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_emr_cluster.go:1391 +0x3b4
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc4209d7140, 0xc4201e78f0, 0xc4204dd340, 0xc4207765a0, 0xc42060a8b8, 0xc42060a8b0)
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x4e0
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: created by github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
2018-04-09T18:28:19.068Z [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1d0
```

### Expected Behavior

After failed cluster creation, error message output.

### Actual Behavior

Panic! 💥 

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
This has been released in [version 1.14.1 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1141-april-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
