### ISSUE TITLE
resource/azurerm_storage_account crash with unexpected EOF

### ISSUE THREAD

**Issue by kalyanrajsista** [terraform-providers/terraform-provider-aws#5096]
### Terraform Version

$ terraform -v
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.azurerm v1.8.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0
+ provider.ultradns v0.1.0

### Affected Resource(s)

module.storage_accounts.azurerm_storage_account.configuration-sa: azurerm_storage_account.configuration-sa: unexpected EOF

**Comment by bflad** [comment]
Hi @kalyanrajsista 👋 Sorry you ran into this unexpected issue.

Since `terraform -v` is not showing the `aws` provider above, it appears you have an issue with one of the other providers crashing (archive, azurerm, external, null, random, template, or ultradns) crashing. The  `unexpected EOF` error can sometimes be misleading about which resource, data source, or provider caused the issue. Can you check to see if Terraform created a `crash.log` file and post its contents (preferably a link to a [GitHub Gist](https://gist.github.com/)) so we can help direct you to the correct place?

**Comment by kalyanrajsista** [comment]
I am using `azurerm` not `aws`

**Comment by bflad** [comment]
@kalyanrajsista according to the crash.log output, the crash is occurring in the `azurerm` provider:

```
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: panic: runtime error: index out of range
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: 
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: goroutine 685 [running]:
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.parseAzureStorageAccountConnectionString(0xc04261a400, 0x18, 0x4, 0x4, 0xc04233a2e8)
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_storage_account_sas.go:377 +0x568
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.dataSourceArmStorageAccountSasRead(0xc0422acaf0, 0x1cde280, 0xc042450000, 0xc0422acaf0, 0x0)
2018-07-05T16:56:12.016-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.8.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_storage_account_sas.go:202 +0x6b1
```

Unfortunately I cannot migrate this GitHub issue automatically for you, but you will want to open in the AzureRM provider repository for your issue with the above information: https://github.com/terraform-providers/terraform-provider-azurerm/issues
