### ISSUE TITLE
resource/aws_wafregional_byte_match_set: Unable to detect byte_match_tuple drift

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#5372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.11.7
Terraform AWS Provider 1.29.0

### Affected Resource(s)

* aws_wafregional_byte_match_set

### Terraform Configuration Files

```hcl
resource "aws_wafregional_byte_match_set" "set" {
  name = "example"
  byte_match_tuple {
    text_transformation   = "NONE"
    target_string         = "badrefer1"
    positional_constraint = "CONTAINS"

    field_to_match {
      type = "HEADER"
      data = "referer"
    }
  }
}
```

### Debug Output

Discovered via `TF_SCHEMA_PANIC_ON_ERROR=1`

```
=== RUN   TestAccAWSWafRegionalRateBasedRule_changePredicates
panic: Invalid address to set: []string{"byte_match_tuple", "0", "field_to_match"}

goroutine 5479 [running]:
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).Set(0xc4209716c0, 0x3e889bd, 0x10, 0x34a6a60, 0xc42057d060, 0x1, 0x9)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:191 +0x237
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsWafRegionalByteMatchSetRead(0xc4209716c0, 0x3938260, 0xc420192900, 0x0, 0xc420266570)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_wafregional_byte_match_set.go:153 +0x448
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsWafRegionalByteMatchSetUpdate(0xc4209716c0, 0x3938260, 0xc420192900, 0xc4207a3f10, 0x0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_wafregional_byte_match_set.go:214 +0x2d9
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsWafRegionalByteMatchSetCreate(0xc4209716c0, 0x3938260, 0xc420192900, 0xc4209716c0, 0x0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_wafregional_byte_match_set.go:129 +0x254
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420238380, 0xc420672280, 0xc4205593c0, 0x3938260, 0xc420192900, 0xc42079a001, 0x42, 0x0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x35a
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42025e2a0, 0xc420bca4b0, 0xc420672280, 0xc4205593c0, 0x1, 0xc4209a56d8, 0xc42091aab0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*EvalApply).Eval(0xc420a3a2c0, 0x42ac040, 0xc4206f8270, 0x2, 0x2, 0x3e6bf7e, 0x4)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval_apply.go:57 +0x22c
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x4272140, 0xc420a3a2c0, 0x42ac040, 0xc4206f8270, 0x0, 0x0, 0x0, 0x0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc420558280, 0x42ac040, 0xc4206f8270, 0x2, 0x2, 0x3e6bf7e, 0x4)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x7a
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x4272680, 0xc420558280, 0x42ac040, 0xc4206f8270, 0x37aff00, 0x61a07a2, 0x34f4b00, 0xc4206c7cd0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.Eval(0x4272680, 0xc420558280, 0x42ac040, 0xc4206f8270, 0xc420558280, 0x4272680, 0xc420558280, 0xc420845be0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x3db79e0, 0xc4204f0460, 0x0, 0x0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/graph.go:126 +0xc26
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc420c98230, 0x3db79e0, 0xc4204f0460, 0xc4204fd3c0)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag/walk.go:387 +0x3a0
created by github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag.(*Walker).Update
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag/walk.go:310 +0x1248
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	128.108s
```

### Expected Behavior

Successfully reads API and updates `byte_match_tuple` in Terraform state

### Actual Behavior

Silently unable to update `byte_match_tuple` in Terraform state to detect drift

### Steps to Reproduce

1. `export TF_SCHEMA_PANIC_ON_ERROR=1`
2. `make testacc TEST=./aws TESTARGS='-run=TestAccAWSWafRegionalRateBasedRule_changePredicates'`

**Comment by bflad** [comment]
This has been released in [version 1.37.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1370-september-19-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
