### ISSUE TITLE
aws_db_instance -- Creating Instance From Snapshot Fails on 1.30

### ISSUE THREAD

**Issue by myoung34** [terraform-providers/terraform-provider-aws#5477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

TF 0.11.7
TF aws provider 1.30.0

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "default" {
  allocated_storage           = "${var.storage_size}"
  allow_major_version_upgrade = "${var.allow_major_version_upgrade}"
  apply_immediately           = "${var.apply_immediately}"
  auto_minor_version_upgrade  = "${var.auto_minor_version_upgrade}"
  backup_retention_period     = "${var.retention_period}"
  backup_window               = "${var.backup_window}"
  db_subnet_group_name        = "${aws_db_subnet_group.default.id}"
  engine                      = "${var.engine}"
  engine_version              = "${var.engine_version}"
  final_snapshot_identifier   = "${var.final_snapshot_identifier}"
  identifier                  = "${var.name}"
  instance_class              = "${var.instance_class}"
  maintenance_window          = "${var.maintenance_window}"
  multi_az                    = "${var.multi_az}"
  name                        = "${var.db_name}"
  parameter_group_name        = "${aws_db_parameter_group.default.name}"
  skip_final_snapshot         = "${var.skip_final_snapshot}"
  snapshot_identifier         = "${var.snapshot_identifier}"
  storage_encrypted           = "${var.encrypted}"

  lifecycle {
    ignore_changes = ["snapshot_identifier"]
  }

  tags {
    Environment = "${var.environment}"
    Managed_by  = "terraform"
  }

  vpc_security_group_ids = ["${var.security_group_ids}"]
}
```

```hcl
variable "allow_major_version_upgrade" {
  default = "true"
}

variable "auto_minor_version_upgrade" {
  default = "true"
}

variable "alarm_actions" {
  type    = "list"
  default = []
}

variable "ok_actions" {
  type    = "list"
  default = []
}

variable "apply_immediately" {
  default = "false"
}

variable "backup_window" {
  default = "02:00-03:00"
}

variable "db_name" {}

variable "encrypted" {
  default = "true"
}

variable "engine" {
  default = "postgres"
}

variable "engine_version" {
  default = "9.6.6"
}

variable "environment" {}

variable "family" {
  default = "postgres9.6"
}

variable "final_snapshot_identifier" {}

variable "instance_class" {
  default = "db.t2.large"
}

variable "maintenance_window" {
  default = "Sat:03:00-Sat:04:00"
}

variable "multi_az" {
  default = "false"
}

variable "name" {}

variable "parameters" {
  description = "A list of DB parameter maps to apply"

  default = [
    {
      name  = "log_statement"
      value = "all"
    },
    {
      name  = "log_min_duration_statement"
      value = "1"
    },
  ]
}

variable "retention_period" {
  default = "14"
}

variable "security_group_ids" {
  type = "list"
}

variable "skip_final_snapshot" {
  default = "false"
}

variable "snapshot_identifier" {}

variable "storage_size" {
  default = "100"
}

variable "subnet_ids" {
  type = "list"
}
```

```hcl
module "rds" {
  source = "../../../../modules/rds/snapshot"

  apply_immediately         = "true"
  engine_version            = "9.6.6"
  environment               = "staging"
  final_snapshot_identifier = "health-staging-final-5"
  instance_class            = "db.m3.medium"
  name                      = "health-staging"
  db_name                   = "${data.vault_generic_secret.rds_dbname.data["value"]}"
  skip_final_snapshot       = "true"
  security_group_ids        = ["${data.terraform_remote_state.staging_vpc.default_security_group_id}"]
  snapshot_identifier       = "${var.rds_snapshot_identifier}"
  storage_size              = "150"
  subnet_ids                = ["${data.terraform_remote_state.staging_vpc.private_subnet_ids}"]
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Create an aws_db_instance from a snapshot

### Actual Behavior

```
5:38:50 module.rds.aws_db_instance.default: Creating...
05:38:50   address:                           "" => "<computed>"
05:38:50   allocated_storage:                 "" => "150"
05:38:50   allow_major_version_upgrade:       "" => "true"
05:38:50   apply_immediately:                 "" => "true"
05:38:50   arn:                               "" => "<computed>"
05:38:50   auto_minor_version_upgrade:        "" => "true"
05:38:50   availability_zone:                 "" => "<computed>"
05:38:50   backup_retention_period:           "" => "14"
05:38:50   backup_window:                     "" => "02:00-03:00"
05:38:50   ca_cert_identifier:                "" => "<computed>"
05:38:50   character_set_name:                "" => "<computed>"
05:38:50   copy_tags_to_snapshot:             "" => "false"
05:38:50   db_subnet_group_name:              "" => "health-staging"
05:38:50   endpoint:                          "" => "<computed>"
05:38:50   engine:                            "" => "postgres"
05:38:50   engine_version:                    "" => "9.6.6"
05:38:50   final_snapshot_identifier:         "" => "health-staging-final-5"
05:38:50   hosted_zone_id:                    "" => "<computed>"
05:38:50   identifier:                        "" => "health-staging"
05:38:50   identifier_prefix:                 "" => "<computed>"
05:38:50   instance_class:                    "" => "db.m3.medium"
05:38:50   kms_key_id:                        "" => "<computed>"
05:38:50   license_model:                     "" => "<computed>"
05:38:50   maintenance_window:                "" => "sat:03:00-sat:04:00"
05:38:50   monitoring_interval:               "" => "0"
05:38:50   monitoring_role_arn:               "" => "<computed>"
05:38:50   multi_az:                          "" => "false"
05:38:50   name:                              "" => "db6t9t6pdmhs5t"
05:38:50   option_group_name:                 "" => "<computed>"
05:38:50   parameter_group_name:              "" => "health-staging"
05:38:50   port:                              "" => "<computed>"
05:38:50   publicly_accessible:               "" => "false"
05:38:50   replicas.#:                        "" => "<computed>"
05:38:50   resource_id:                       "" => "<computed>"
05:38:50   skip_final_snapshot:               "" => "true"
05:38:51   snapshot_identifier:               "" => "rds:health-prod-2018-08-07-02-05"
05:38:51   status:                            "" => "<computed>"
05:38:51   storage_encrypted:                 "" => "true"
05:38:51   storage_type:                      "" => "<computed>"
05:38:51   tags.%:                            "" => "2"
05:38:51   tags.Environment:                  "" => "staging"
05:38:51   tags.Managed_by:                   "" => "terraform"
05:38:51   timezone:                          "" => "<computed>"
05:38:51   username:                          "" => "<computed>"
05:38:51   vpc_security_group_ids.#:          "" => "1"
05:38:51   vpc_security_group_ids.1780067147: "" => "sg-021bb2dc059252e0f"
```

```
05:54:42 Error: Error applying plan:
05:54:42 
05:54:42 1 error(s) occurred:
05:54:42 
05:54:42 * module.rds.aws_db_instance.default: 1 error(s) occurred:
05:54:42 
05:54:42 * aws_db_instance.default: InvalidParameterValue: The parameter ResourceName must be provided and must not be blank.
05:54:42 	status code: 400, request id: 3b05a927-738a-4afe-8322-863e877bcedc
05:54:42 
05:54:42 Terraform does not automatically rollback in the face of errors.
05:54:42 Instead, your Terraform state file has been partially updated with
05:54:42 any resources that successfully completed. Please address the error
05:54:42 above and apply again to incrementally change your infrastructure.
05:54:42 
05:54:42 
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Works in <= 1.26

### References

* #5450
* #5360

**Comment by bflad** [comment]
Hi @myoung34 👋  Can you determine which API call is generating the error from [enabling debug logging](https://www.terraform.io/docs/internals/debugging.html)? Thanks! Its very curious that the `snapshot_identifier` + `tags` fix that went in with https://github.com/terraform-providers/terraform-provider-aws/issues/5370 and released with version 1.30.0 didn't catch this as there's not too many places in the RDS resources that have `ResourceName` as a parameter.

**Comment by bflad** [comment]
@myoung34 ping 😄

**Comment by myoung34** [comment]
@bflad 

```
vault_database_secret_backend_connection.rds: Modifying... (ID: database/config/rds-staging)
  postgresql.0.connection_url: "postgresql://username:*****@health-staging.redact.us-east-1.rds.amazonaws.com:5432/db6t9t6pdmhs5t" => "postgresql://username:password@health-staging.redact.us-east-1.rds.amazonaws.com:5432/db6t9t6pdmhs5t"
2018-08-20T09:47:20.631-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:20 [DEBUG] Writing connection config to "database/config/rds-staging"
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:20 [DEBUG] Vault API Request Details:
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: ---[ REQUEST ]---------------------------------------
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: PUT /v1/database/config/rds-staging HTTP/1.1
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Host: vault.redact.com:8200
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: User-Agent: Go-http-client/1.1
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Content-Length: 332
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: X-Vault-Token: 02f7f2e1-3a87-1e42-0223-1d469538f0bc
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Accept-Encoding: gzip
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:20.632-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: -----------------------------------------------------
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:20 [DEBUG] Vault API Response Details:
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: ---[ RESPONSE ]--------------------------------------
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: HTTP/1.1 200 OK
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Connection: close
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Content-Length: 288
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Cache-Control: no-store
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Content-Type: application/json
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Date: Mon, 20 Aug 2018 14:47:20 GMT
2018-08-20T09:47:20.959-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: -----------------------------------------------------
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:20 [DEBUG] Wrote database connection config "database/config/rds-staging"
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:20 [DEBUG] Reading database connection config "database/config/rds-staging"
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:20 [DEBUG] Vault API Request Details:
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: ---[ REQUEST ]---------------------------------------
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: GET /v1/database/config/rds-staging HTTP/1.1
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Host: vault.redact.com:8200
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: User-Agent: Go-http-client/1.1
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: X-Vault-Token: 02f7f2e1-3a87-1e42-0223-1d469538f0bc
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Accept-Encoding: gzip
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:20.960-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: -----------------------------------------------------
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:21 [DEBUG] Vault API Response Details:
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: ---[ RESPONSE ]--------------------------------------
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: HTTP/1.1 200 OK
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Connection: close
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Content-Length: 507
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Cache-Control: no-store
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Content-Type: application/json
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: Date: Mon, 20 Aug 2018 14:47:21 GMT
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: -----------------------------------------------------
2018-08-20T09:47:21.126-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: 2018/08/20 09:47:21 [DEBUG] Read database connection config "database/config/rds-staging"
2018-08-20T09:47:21.128-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: panic: interface conversion: interface {} is string, not json.Number
2018-08-20T09:47:21.128-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:
2018-08-20T09:47:21.128-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: goroutine 208 [running]:
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.getConnectionDetailsFromResponse(0xc4203d4f60, 0x1a, 0xc6bb73, 0x1a)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_database_secret_backend_connection.go:346 +0x81b
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.databaseSecretBackendConnectionRead(0xc42017c620, 0xc2b600, 0xc420541ad0, 0x1, 0x1)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_database_secret_backend_connection.go:505 +0x100b
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.databaseSecretBackendConnectionUpdate(0xc42017c620, 0xc2b600, 0xc420541ad0, 0x24, 0x1173f60)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_database_secret_backend_connection.go:560 +0x746
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4204baf60, 0xc420140190, 0xc4204a69a0, 0xc2b600, 0xc420541ad0, 0x1, 0xc4205406f0, 0xc420143170)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:199 +0x2ab
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42009f570, 0xc420140140, 0xc420140190, 0xc4204a69a0, 0x7f24e7164458, 0x0, 0x18)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0xa4
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4203392a0, 0xc4204a6580, 0xc4203f5210, 0x0, 0x0)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: reflect.Value.call(0xc4202ba300, 0xc420136500, 0x13, 0xc58813, 0x4, 0xc420050f20, 0x3, 0x3, 0x493178, 0xc420366888, ...)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /usr/local/go/src/reflect/value.go:434 +0x905
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: reflect.Value.Call(0xc4202ba300, 0xc420136500, 0x13, 0xc4204f1f20, 0x3, 0x3, 0xc4204f1f9e, 0xc4204f1f98, 0x0)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /usr/local/go/src/reflect/value.go:302 +0xa4
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: net/rpc.(*service).call(0xc420485f00, 0xc420140fa0, 0xc4204f6890, 0xc4202dc880, 0xc420212d40, 0xaf7460, 0xc4204a6580, 0x16, 0xaf74a0, 0xc4203f5210, ...)
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /usr/local/go/src/net/rpc/server.go:381 +0x142
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4: created by net/rpc.(*Server).ServeCodec
2018-08-20T09:47:21.129-0500 [DEBUG] plugin.terraform-provider-vault_v1.1.0_x4:         /usr/local/go/src/net/rpc/server.go:475 +0x36b
2018/08/20 09:47:21 [TRACE] root: eval: *terraform.EvalWriteState
2018-08-20T09:47:21.132-0500 [DEBUG] plugin: plugin process exited: path=/home/marc/repos/redact/ops/terraform/app/health/webserver/staging/.terraform/plugins/linux_amd64/terraform-provider-vault_v1.1.0_x4
2018/08/20 09:47:21 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/08/20 09:47:21 [TRACE] root: eval: *terraform.EvalIf
2018/08/20 09:47:21 [TRACE] root: eval: *terraform.EvalWriteState
2018/08/20 09:47:21 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/08/20 09:47:21 [TRACE] root: eval: *terraform.EvalApplyPost
2018/08/20 09:47:21 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vault_database_secret_backend_connection.rds: unexpected EOF
2018/08/20 09:47:21 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vault_database_secret_backend_connection.rds: unexpected EOF
2018/08/20 09:47:21 [TRACE] [walkApply] Exiting eval tree: vault_database_secret_backend_connection.rds
2018/08/20 09:47:21 [TRACE] dag/walk: upstream errored, not walking "provider.vault (close)"
2018/08/20 09:47:21 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/08/20 09:47:21 [TRACE] dag/walk: upstream errored, not walking "root"
2018/08/20 09:47:21 [TRACE] Preserving existing state lineage "9b4fb23a-fbee-4dd5-8844-921410cad5b0"
2018/08/20 09:47:21 [TRACE] Preserving existing state lineage "9b4fb23a-fbee-4dd5-8844-921410cad5b0"
2018/08/20 09:47:21 [TRACE] Preserving existing state lineage "9b4fb23a-fbee-4dd5-8844-921410cad5b0"
2018/08/20 09:47:21 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc4207b4e10),
  Bucket: "com-redact-terraform",
  ContentLength: 161411,
  ContentType: "application/json",
  Key: "app/health/webserver/staging/terraform.tfstate"
}
```
