### ISSUE TITLE
aws_alb_listener undefined local variable or method `host'

### ISSUE THREAD

**Issue by andrewhertog** [terraform-providers/terraform-provider-aws#5661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.33.0
```

### Affected Resource(s)

* aws_alb_listener

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_alb_listener" "default_listener" {
  default_action {
    type = "redirect"
    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
  }

  load_balancer_arn = "${aws_alb.current_alb.arn}"
  port              = 80
  protocol          = "HTTP"
}
```

### Debug Output

https://gist.github.com/andrewhertog/077efa8e3891b95a03b2697fa7ae815c

### Expected Behavior

It should change the listener from the default target listener type to a redirect listener type

### Actual Behavior

```
~ module.alb.aws_alb_listener.default_listener
    default_action.0.redirect.#:               "0" => "1"
/usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:167:in `eval': undefined local variable or method `host' for #<TerraformLandscape::TerraformPlan:0x00007fc0a29a7cb0> (NameError)
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:167:in `eval'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:167:in `display_modified_attribute'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:141:in `display_attribute'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:89:in `block in display_resource'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:86:in `each'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:86:in `display_resource'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:60:in `block in display'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:59:in `each'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/terraform_plan.rb:59:in `display'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/printer.rb:76:in `process_string'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/printer.rb:35:in `process_stream'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/cli.rb:48:in `print'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/cli.rb:34:in `block (2 levels) in define_commands'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/commander-4.4.5/lib/commander/command.rb:182:in `call'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/commander-4.4.5/lib/commander/command.rb:153:in `run'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/commander-4.4.5/lib/commander/runner.rb:446:in `run_active_command'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/commander-4.4.5/lib/commander/runner.rb:68:in `run!'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/commander-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/lib/terraform_landscape/cli.rb:25:in `run'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/gems/terraform_landscape-0.1.18/bin/landscape:7:in `<top (required)>'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/bin/landscape:22:in `load'
        from /usr/local/Cellar/terraform_landscape/0.1.18/libexec/bin/landscape:22:in `<main>'
```

### Steps to Reproduce

1. Create an ALB with a listener default action of "forward":
```hcl 
resource "aws_alb_listener" "default_listener" {
  "default_action" {
    target_group_arn = "${aws_alb_target_group.default_target_group.arn}"
    type             = "forward"
  }

  load_balancer_arn = "${aws_alb.current_alb.arn}"
  port              = 80
  protocol          = "HTTP”
}
```
2. `terraform apply`
3. Modify your config so that it redirects
```hcl
resource "aws_alb_listener" "default_listener" {
  default_action {
    type = "redirect"
    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
  }

  load_balancer_arn = "${aws_alb.current_alb.arn}"
  port              = 80
  protocol          = "HTTP”
}
```
4. `terraform plan` should show the error 

### References

* #5430

**Comment by bflad** [comment]
The error provided above seems to be coming from https://github.com/coinbase/terraform-landscape -- what is the error provided with `terraform plan`?

**Comment by andrewhertog** [comment]
Removing landscape seems to have fixed the issue. Thanks
