### ISSUE TITLE
Panic in provider

### ISSUE THREAD

**Issue by crawford** [terraform-providers/terraform-provider-aws#6307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

Unsure

### Terraform Configuration Files

I don't have a minimal repro.

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c657ed]               
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:                                                                                                                                                                                 
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: goroutine 1181 [running]:                                                                  
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenAwsLbTargetGroupResource(0xc4202938f0, 0x24fd280, 0xc4201f8a00, 0xc420e18510, 0x0, 0xc4205acf30)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:529 +0x62d                            
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc4202938f0, 0x24fd280, 0xc4201f8a00, 0x0, 0x0)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:273 +0x28b
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupUpdate(0xc4202938f0, 0x24fd280, 0xc4201f8a00, 0x0, 0x0)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:371 +0x178
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupCreate(0xc4202938f0, 0x24fd280, 0xc4201f8a00, 0xc4202938f0, 0x0)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:251 +0x8f9
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420c92380, 0xc420196500, 0xc4208f3ea0, 0x24fd280,
0xc4201f8a00, 0x1, 0xc4206528d0, 0xc4206528d0)                                                                                                                      
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x364
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420c924d0, 0xc4201964b0, 0xc420196500, 0xc4208f3ea
0, 0x7f5803e1d000, 0x0, 0x0)                                                                                                     
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420642040, 0xc4208f3e20, 0xc420a24930, 0x0,
 0x0)                                                                                                                                                                 
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: reflect.Value.call(0xc4203a6840, 0xc420536018, 0x13, 0x28f602e, 0x4, 0xc420810f20, 0x3, 0x3, 0xc4204bcf28, 0x1, ...)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /usr/local/go/src/reflect/value.go:434 +0x905
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: reflect.Value.Call(0xc4203a6840, 0xc420536018, 0x13, 0xc4204bcf20, 0x3, 0x3, 0x43e5ec0, 0xc42090c780, 0xc420379360)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /usr/local/go/src/reflect/value.go:302 +0xa4                  
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: net/rpc.(*service).call(0xc420da0080, 0xc4205f60f0, 0xc4206c6030, 0xc4205f8000, 0xc4208af4a0, 0x2071fe0, 0xc4208f3e20, 0x16, 0x2072020, 0xc420a24930, ...)
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /usr/local/go/src/net/rpc/server.go:381 +0x142                                      
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: created by net/rpc.(*Server).ServeCodec                               
2018-10-30T15:23:00.267-0700 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:   /usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by crawford** [comment]
Well, this is embarrassing. I realized I was using 1.8.0 of the provider. Bumping to 1.39.0 will almost certainly fix this issue.
