### ISSUE TITLE
Crash on terraform apply in v0.12.3

### ISSUE THREAD

**Issue by confiq** [terraform-providers/terraform-provider-aws#9260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.3
+ provider.aws v2.18.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_2.18.0

### Terraform Configuration Files

I'm trying to convert my code base from 0.11 to 0.12. 
So it's a big part of the code and I can't pinpoint exactly where does it crash.

### Panic Output

```
panic: interface conversion: interface {} is []interface {}, not string
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4:
2019/07/07 17:11:06 [TRACE] module.console_platform: eval: *terraform.EvalCheckPreventDestroy
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: goroutine 412 [running]:
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence.newAWSStringSet(0x4890a80, 0xc000a3fd40, 0xc000478ac0, 0x4, 0x4)
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence/aws_policy_equivalence.go:386 +0x22e
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence.(*awsPolicyStatement).equals(0xc0005bf830, 0xc0005bf950, 0x0)
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence/aws_policy_equivalence.go:176 +0x2d8
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence.(*awsPolicyDocument).equals(0xc000478a00, 0xc000478a80, 0x0)
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence/aws_policy_equivalence.go:114 +0xea
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence.PoliciesAreEquivalent(0xc0007d02c0, 0x294, 0xc000aeac80, 0x24d, 0x100e429, 0xc000743530, 0xc000844c60)
2019-07-07T17:11:06.696+0200 [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence/aws_policy_equivalence.go:50 +0x520
```

I would like to avoid to upload the whole log because it's 22MB big and I don't want to leak any internal infra info to interwebs 
### Actual Behavior
Terraform crash

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by confiq** [comment]
still happens with newest version of aws (2.19) 

```
panic: interface conversion: interface {} is []interface {}, not string
2019-07-17T11:56:08.461+0200 [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4:
2019-07-17T11:56:08.461+0200 [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4: goroutine 439 [running]:
2019-07-17T11:56:08.461+0200 [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence.newAWSStringSet(0x48d0740, 0xc000a47760, 0xc000b90a00, 0x4, 0x4)
2019/07/17 11:56:08 [TRACE] Completed graph transform *terraform.ResourceCountTransformer with new graph:
module.bussola_service.aws_iam_policy.bussola_geocoder_lambda_sqs_control - *terraform.NodePlannableResourceInstance
```

**Comment by confiq** [comment]
I think I can isolate the problem


```terraform
locals {
  bucket_resources = [concat(list("arn:aws:s3:::xxx*"))]

}

# relevent only to QA
resource "aws_iam_user_policy" "ops_admin_user_policy" {
  name = "xxxx"
  user = module.ops_admin_host.backend_user_name

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:ListBucket",
        "s3:PutObject",
        "s3:GetObject",
        "s3:GetObjectVersion",
        "s3:DeleteObject",
        "s3:DeleteObjectVersion"
      ],
      "Resource": ${jsonencode(local.bucket_resources)}
    }
  ,
    {
      "Effect": "Allow",
      "Action": "cloudfront:CreateInvalidation",
      "Resource": "*"
    }
  ]
}
EOF
}

```

This will cause to crash! 
If the variable `bucket_resources` is string it will work nice! 

I'm not sure the problem is aws provider anymore. Should I open a ticket to upstream?

**Comment by ryndaniels** [comment]
Hi @confiq - thanks for opening this issue, and for the work you've done so far to isolate the problem! I suspect you may be right with this being an upstream issue at this point, however, I'm not able to reproduce the crash with a more recent Terraform version (I'm using v0.12.6). Before you open an upstream issue, could I get you to try with the most recent version of Terraform (I believe now that's v0.12.7) and see if you're still running into this? Thanks! 🙂

**Comment by confiq** [comment]
I can't reproduce anymore with version `Terraform v0.12.7`  :) 
It seems they've fix it!

**Comment by ryndaniels** [comment]
Awesome, glad to hear it! 👍
